stages:
  - setup
  - build
  - test

variables:
  # Remove GOPATH to avoid conflicts with Go modules
  # GOPATH: "$CI_PROJECT_DIR"
  GO111MODULE: "on"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - go/pkg/mod
    - go/bin
    - go.sum
    - go.mod

before_script:
  - go version

setup_module:
  stage: setup
  image: golang:1.20-bullseye
  script:
    - echo "Initializing Go module"
    - go mod init strip_pcap || true
    - go get github.com/google/gopacket
    - go mod tidy
  artifacts:
    paths:
      - go.mod
      - go.sum



build_macos:
  stage: build
  image: golang:1.20-bullseye
  needs:
    - setup_module
  script:
    - echo "Building on macOS ARM"
    - GOOS=darwin GOARCH=arm64 go build -o strip_pcap_macos_arm strip_pcap.go
  artifacts:
    paths:
      - strip_pcap_macos_arm
